name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev
      - test

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
